# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1zp0wm7lk0gijrlmb8p8g9al9q451lsaya17bp3wc2k73mp69q65";
    armv7l-linux = "043q5xihqynjwm3jq2qngawb2farpilgv1cngbrhk95dh8r5k0j0";
    aarch64-linux = "12l3g90j4qp2fkrwk9n4090bkl1csqk5ljlxwpr35v1f2zxmzyil";
    x86_64-darwin = "1z8knnrcv7s70bkk2vpqa9qb59xiaywkml7dwmbckp5b8cspm5y2";
    aarch64-darwin = "0l5rsi9n0iv31mr3ac4rs96w4gidl00y8717hijgdhbdwngf2hpc";
  };

  urlMap = {
    x86_64-linux = "https://dl.dagger.io/dagger/releases/0.16.0-llm.2/dagger_v0.16.0-llm.2_linux_amd64.tar.gz";
    armv7l-linux = "https://dl.dagger.io/dagger/releases/0.16.0-llm.2/dagger_v0.16.0-llm.2_linux_armv7.tar.gz";
    aarch64-linux = "https://dl.dagger.io/dagger/releases/0.16.0-llm.2/dagger_v0.16.0-llm.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://dl.dagger.io/dagger/releases/0.16.0-llm.2/dagger_v0.16.0-llm.2_darwin_amd64.tar.gz";
    aarch64-darwin = "https://dl.dagger.io/dagger/releases/0.16.0-llm.2/dagger_v0.16.0-llm.2_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dagger";
  version = "0.16.0-llm.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ././dagger $out/bin/./dagger
  '';
  postInstall = ''
    installShellCompletion --cmd dagger \
    --bash <($out/bin/dagger completion bash) \
    --fish <($out/bin/dagger completion fish) \
    --zsh <($out/bin/dagger completion zsh)
  '';

  system = system;

  meta = {
    description = "Dagger is an integrated platform to orchestrate the delivery of applications";
    homepage = "https://dagger.io";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
