# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0gwb9ld92762rm83gajzh8jpc6d4iysxzn0h1x38qzvlklpfw5ar";
    armv7l-linux = "0k9a66cf74p9g5c4zha08lkvh8xdd6ydn6pc0fhrvnnn60lc3abj";
    aarch64-linux = "0c6n0x36317nys9yd5kj295fgx8fv0khvsk2g1fprd49f4gw036x";
    x86_64-darwin = "0mr7kmcz5np3vdg1rzpj6m3fsjsmycx3yypgz65jh2kz4xh4ngnh";
    aarch64-darwin = "03s40iwasv94ppi256324z0qhzv78nljvrkvfxw1lc5dsjwdgvr3";
  };

  urlMap = {
    x86_64-linux = "https://dl.dagger.io/dagger/releases/0.18.15/dagger_v0.18.15_linux_amd64.tar.gz";
    armv7l-linux = "https://dl.dagger.io/dagger/releases/0.18.15/dagger_v0.18.15_linux_armv7.tar.gz";
    aarch64-linux = "https://dl.dagger.io/dagger/releases/0.18.15/dagger_v0.18.15_linux_arm64.tar.gz";
    x86_64-darwin = "https://dl.dagger.io/dagger/releases/0.18.15/dagger_v0.18.15_darwin_amd64.tar.gz";
    aarch64-darwin = "https://dl.dagger.io/dagger/releases/0.18.15/dagger_v0.18.15_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dagger";
  version = "0.18.15";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ././dagger $out/bin/./dagger
  '';
  postInstall = ''
    installShellCompletion --cmd dagger \
    --bash <($out/bin/dagger completion bash) \
    --fish <($out/bin/dagger completion fish) \
    --zsh <($out/bin/dagger completion zsh)
  '';

  system = system;

  meta = {
    description = "Dagger is an integrated platform to orchestrate the delivery of applications";
    homepage = "https://dagger.io";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
